### ISSUE TITLE
[Footer] Add social links

### ISSUE THREAD

**Issue by dev-launchers-sandbox** [dev-launchers/platform__website#102]
We're adding more and more social accounts and building communities in different places. We'd like to have icons with links to each of these in the footer:

Instagram: https://www.instagram.com/devlaunchers/
Twitch: https://www.twitch.tv/devlaunchers
Discord: https://discord.io/devlaunchers

**Comment by chungthuang** [comment]
We also have a LinkedIn page https://www.linkedin.com/company/devlaunchers/!

**Comment by pyxld-kris** [comment]
Good call! We should definitely get that on there
