### ISSUE TITLE
[CheckIt Page] Create route with all pertinent links we may direct people to

### ISSUE THREAD

**Issue by pyxld-kris** [dev-launchers/platform__website#103]
Route will live at https://devlaunchers.com/#/check-it

We can add more to this as we grow, for now we'd like to have links, with descriptions, to:

 - Discord: https://discord.io/devlaunchers/
 - Twitch: https://twitch.tv/devlaunchers/
 - Instagram: https://instagram.com/devlaunchers/
 - Project Showcase: https://devlaunchers.com/#/play/
 - Hangout Link: https://devlaunchers.com/#/hangout/
 - LinkedIn: https://www.linkedin.com/company/devlaunchers/

**Comment by elitejam** [comment]
https://github.com/dev-launchers/platform__website/pull/141

Pull request in progress. See link above.

**Comment by pyxld-kris** [comment]
Closed with #141
