### ISSUE TITLE
Implement mentor signup form

### ISSUE THREAD

**Issue by chungthuang** [dev-launchers/platform__website#120]
**Is your feature request related to a problem? Please describe.**
We have a **Become A Mentor** button on the home page, but right now it says site is currently under development after clicking it. 

**Describe the solution you'd like**
It should bring potential mentors to a signup page. 

**Describe alternatives you've considered**
A link to a Google form, but that will leave us with little room to improve the UX. 

**Additional context**
The signup page should ask for at least name, contact information and level of experience. We can use a Google sheet as backend for the signups.

**Comment by chungthuang** [comment]
@pyxld-kris suggests if we choose to use Google form, we can make it look nicer with https://stackoverflow.com/questions/37184582/is-there-a-way-to-edit-css-of-new-google-forms.

**Comment by pyxld-kris** [comment]
Closed with #123
