### ISSUE TITLE
[Members Route] Convert accordion menu to cards

### ISSUE THREAD

**Issue by dev-launchers-sandbox** [dev-launchers/platform__website#147]
#### We'd like to touch up the members page, and add new pretty images!

![image](https://user-images.githubusercontent.com/53383188/89485296-13f9de80-d766-11ea-8403-db15b894cdf3.png)

When clicked, cards should open a modal with relevant information for each level
![image](https://user-images.githubusercontent.com/53383188/89485349-3b50ab80-d766-11ea-851d-f8cbf6382acf.png)

**Comment by pyxld-kris** [comment]
Closed with #149 and #150
