### ISSUE TITLE
Add prettier?

### ISSUE THREAD

**Issue by third774** [dev-launchers/platform__website#16]
Hey there! Was gonna start taking a look at some of the issues to work on and realized the project isn't set up to use Prettier. How would y'all feel about me setting that up? We could also add a pre-commit hook that formats code before committing so contributors who don't use it can't get non-formatted code in?

**Comment by pyxld-kris** [comment]
Your prettier pull request is up, and very much appreciated. The hook sounds great as well. Anything else you'd like to throw out that you think would make life better for contributors is welcome, and I'm happy to take on whatever tasks are needed to make that happen!
