### ISSUE TITLE
[JoinRoute and CalendarRoute] Calendar is not responsive

### ISSUE THREAD

**Issue by pyxld-kris** [dev-launchers/platform__website#22]
Currently on mobile and on smaller screens, the calendar is cut off and unusable. Ideally the calendar will adapt to these different screen sizes in some way, and remain usable by site visitors.

**Comment by sydbails** [comment]
https://profromgo.com/blog/google-calendar-responsive/

adding this link so I don't forget to reference it when I try to tackle this.
