### ISSUE TITLE
Events Page: Make title more action oriented

### ISSUE THREAD

**Issue by pyxld-kris** [dev-launchers/platform__website#26]
Right now, all of our page titles are verbs ("Create", "Learn", "Play", etc.) except for our "Events" Page. It would be nice to have a cohesive convention here.

Down the road this page will contain a large collection of in-person events Dev Launchers is hosting. These will include things like: weekly lab sessions with our teen students, meetups for our adult members to hang out and create code or do resume/interview prep, hackathons and game jams, organization hosted events like fundraisers, etc. 

One contending term is "Meet Up". If we can come up something shorter and more concise, even better!

**Comment by sydbails** [comment]
"Attend"
"Join Us" <- (love this one - join is such a great call to action)
"Participate"

**Comment by sydbails** [comment]
I think "Join" could work, too

**Comment by pyxld-kris** [comment]
I really like "Attend" and "Participate", along with the change from "Support Us" to "Support". I have a gut feeling "Join" might be a little ambiguous, especially after we add logins and signups, because it's used across other sites as a sort of universal term for signing up. If not for that, it would probably be top of my list.

**Comment by chungthuang** [comment]
I like "Join" because it feels like you are now part of a community. I'd also like to nominate "embark" and "discover".

**Comment by pyxld-kris** [comment]
Looks like we have two for 'Join'. Shall we go with that, or does anyone want to throw a vote at any of the other nominations? Will close this out in three days and change it to whatever ends up with the most love.

**Comment by chungthuang** [comment]
My final vote is Join Us, I think it gives a sense of joining a community.
