### ISSUE TITLE
{Curriculum Curation} Initial collection of third party learning resources for our students

### ISSUE THREAD

**Issue by pyxld-kris** [dev-launchers/platform__website#27]
Also see: #7 (Implementing the UI/UX for the solution described here)

---

## Problem
We don't currently have enough material on the site to keep students active, engaged, and learning for more than a few sessions. This has a some negative side effects
   - Mentors working on advising students in scopes outside of the mentor's core competencies experience friction due to the lack of structure guiding their interactions
   - Students beginning projects are not as prepared as they could be/don't have enough material to revisit key concepts when they encounter issues in their personal projects. 

We also do not currently have the resources to develop the majority of these activities ourselves. 

---

## Solution
We're carefully curating a collection of third party learning resources and activities which are intended to bolster our students' understanding of core concepts and tools. This will keep them engaged on the learning side of our platform for longer periods of time, and provide more conversation starting points and structure for our mentor-student interactions. 

To accomplish this, we're using Google Sheets as a store to collaboratively collect different resources we believe will aid our students. This sheet will connect directly to our frontend, and as new resources are added the site will update live. 

**Dev Launchers currently offers two main tracks for students: Code and Design. We have separate curated collections for each track.**

The sheet is located here: https://docs.google.com/spreadsheets/d/1QV419fM2DHZM59mFK6eYYbYiq6bs4sBUpTwVZ_dZJNg/edit#gid=0

**Please request access if you'd like to add something!**

---

## Guidelines
There are some guidelines and constraints to take into account when adding new activities/resources. These tie into the overall philosophy of our program, technical issues, limits created with the social dynamics of our in-person sessions in mind, and overall user experience concerns. *If you have any thoughts on these please holler in the comments!*

Our Guidelines:
   - **Focus mostly on interactive activities and lessons.** Video and longform supplements are welcome, but hopefully can be kept short and not make up an overwhelming majority of the curriculum
   - **No sign up required, or sign up using a GitHub or Google Account is available.** Click a link, instantly be thrown into a new activity or lesson
   - **Able to be laid out on our site in discrete, bite sized units.** Not only to keep the students used to using our platform as their central hub, but this also gives us more control over their direction and trajectory with the content they're consuming.
   - **Ensure the resources are applicable to what we're building with the students!** We're currently set up with three categories a resource can fall into: General, Games, and Apps. 

---

## Sources
We're working on creating a collection of quality sources we can use to find individual activities and lessons. Please leave any links in the comments!

   - https://phaser.io/examples

---

## The Future
**In the future, in an effort to keep the experience cohesive and lower cognitive load, our curriculum will be centralized into a few familiar locations as our resource availability increases**

**Comment by bpred754** [comment]
I haven't looked at these resources in a while (looks like simple programmer has free courses), but I found them useful in my beginning years of software development

https://simpleprogrammer.com

https://www.newthinktank.com
