### ISSUE TITLE
Earn Page: Add flair to leader board

### ISSUE THREAD

**Issue by pyxld-kris** [dev-launchers/platform__website#42]
We'd like to add some sort of visual flair to the leader board to further incentivize users to compete. The current idea is to display Bronze, Silver, and Gold crowns next to the names of the third, second, and first place users in the leader board. However, this is very open to interpretation, let's make something fun!

In the future **we'd like this flair to display next to the user's name across the site in different areas and pages, not just the Earn page**. It would be best to create a shared common component to display users and implement it here.

**Comment by dev-launchers-sandbox** [comment]
Closed with #58
