### ISSUE TITLE
Firefox compatibility

### ISSUE THREAD

**Issue by Digital-Coder** [dev-launchers/platform__website#475]
**Describe the bug**
Using firefox latest browser, projects page does not load assets

**Desktop :**
 - OS: windows 10
 - Browser: Firefox
 - Version 89

**To Reproduce**

Download latest firefox browser and go to
[devlaunchers](https://devlaunchers.com/projects) 

**Screenshots**
![Screenshot 2021-06-22 at 11-21-37 https devlaunchers com](https://user-images.githubusercontent.com/31192965/122916677-abe7c300-d34c-11eb-9188-9fcd80e78c5c.png)
![Screenshot 2021-06-22 at 11-06-49 https devlaunchers com](https://user-images.githubusercontent.com/31192965/122916683-adb18680-d34c-11eb-911c-ff3b076a8180.png)

**Expected behavior**

Same page behaviour like in chrome browser
![devlaunchers com_projects](https://user-images.githubusercontent.com/31192965/122917199-46480680-d34d-11eb-96a6-dcac48e9e59b.png)
![devlaunchers com_projects (1)](https://user-images.githubusercontent.com/31192965/122917205-4811ca00-d34d-11eb-8d49-01b66096e6af.png)

**Comment by Enjoy2Live** [comment]
@Digital-Coder thanks for letting us know, it's fixed now :D
