### ISSUE TITLE
[Learn Page] GitHub/Git resources to help students understand Git and GitHub

### ISSUE THREAD

**Issue by dev-launchers-sandbox** [dev-launchers/platform__website#60]
## Is your feature request related to a problem? Please describe.
Git and GitHub are complicated topics, and it would be nice to have a structured solution to helping students understand core concepts related to both.

## Describe the solution you'd like
We'd like to implement a new tab or section with easily approachable activities or explanations, which will guide the students through understanding the core concepts of Git and GitHub. Right now, it seems best to create this in a separate tab on the Learn Page, and then in the future add a better way to create subcategories in our current tab system. 

Some possible resources we've been provided are:
 - https://www.youtube.com/watch?v=nhNq2kIvi9s
 - https://education.github.com/git-cheat-sheet-education.pdf
 - https://www.youtube.com/watch?v=0fKg7e37bQE
 - https://www.notion.so/Introduction-to-GitHub-202af6f64bbd4299b15f238dcd09d2a7

However, none of these resources are perfectly digestible/engaging for our teen students. **It would be nice to have these broken down into different sections we can place on individual cards on our page, so that the students will be able to tackle them in bite sized pieces** The last link in that list might be our best bet, if we're able to break out links to individual sections in the article. 

*Other suggestions to tackling this are very welcome!*

**We're using CodeSandbox to introduce students to Git/GitHub, which has a very limited feature set. If possible, the best solution would be structured to teach most of these concepts through CodeSandbox!**

The most important concepts students should be familiar with in order to begin working on their projects are:
 - Beginner:
    - Viewing their code on GitHub
    - General reasons to use version control
    - How the repo system works (local vs remote and changes to each)
    - Committing/Pushing
 - Intermediate:
    - Fetching/Pulling
    - Branches
    - Collaborating on GitHub
       - Pull Requests
       - Project Boards
 - Advanced
    - Merging Branches/Conflicts

To get them started, just those things in the beginner section should help them work in the environment we're using to create their projects.

All modifications to the Learn Page can be done using the spreadsheet located at: https://docs.google.com/spreadsheets/d/1QV419fM2DHZM59mFK6eYYbYiq6bs4sBUpTwVZ_dZJNg/edit#gid=815710842

If you'd like to make changes to the sheet, please request access here!

**Comment by third774** [comment]
I learned git on Udacity. It looks like the course has changed since I took it, but it was really good back then and I imagine it's still really good.

https://www.udacity.com/course/version-control-with-git--ud123

**Comment by pyxld-kris** [comment]
Thank you @third774!

**Comment by third774** [comment]
Another resource!

https://learngitbranching.js.org/
