### ISSUE TITLE
[Stories Page] Journal of lab sections 

### ISSUE THREAD

**Issue by chungthuang** [dev-launchers/platform__website#70]
**Is your feature request related to a problem? Please describe.**
Potential students, mentors, developers and sponsors can learn more about the value of our labs if we write a blog post about them after each session.

**Describe the solution you'd like**
A list of posts like
https://austinjavascript.com/archive/. They can be written by any attendee to get different perspectives. We can encourage students to submit their posts with points as incentive. The content of the posts can be hosted in the stories repo https://github.com/dev-launchers/stories. 

**Describe alternatives you've considered**

**Additional context**

**Comment by pyxld-kris** [comment]
This could be tackled with the new Blog system we have!
